name: Test

on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test_groovy:
    name: Groovy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0

    - uses: actions/setup-java@d202f5dbf7256730fb690ec59f6381650114feb2 # v1.4.3
      with:
        java-version: '11'

    - name: Run Groovy Tests
      run: |
        cd adopt-github-release
        ./gradlew --info test
